# Generated by Django 6.0.6 on 2026-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_brand',
            field=models.CharField(default='Santoor', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='p_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
