# Generated by Django 6.0.8 on 2026-08-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='suuject',
            new_name='subject',
        ),
    ]
