# Generated by Django 6.0.6 on 2026-07-02 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_role_alter_customeuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customeuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.role'),
        ),
    ]
