# Generated by Django 6.1 on 2026-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Executive', 'Executive'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Luxury', 'Luxury')], max_length=20),
        ),
    ]
