# Generated by Django 6.0.6 on 2026-07-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_country_state_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='Country',
            new_name='country',
        ),
    ]
